--7) Entity Relationship Diagram - Simple Order Manager
CREATE TABLE CLIENT(
ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) UNIQUE NOT NULL,
PHONE VARCHAR(13) NOT NULL
);

CREATE TABLE PRODUCT(
ID INT PRIMARY KEY,
NAME VARCHAR(200) NOT NULL,
DESCRIPTION VARCHAR(500),
PRICE DECIMAL(6,2) NOT NULL,
STOCK INT
);

CREATE TABLE ORDERS(
ID INT PRIMARY KEY,
CLIENT_ID INT NOT NULL,
ORDER_DATE TIMESTAMP,
AMOUNT DECIMAL(10,2) NOT NULL,
FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);

CREATE TABLE ORDER_PRODUCTS(
ID INT PRIMARY KEY,
ORDER_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
QUANTITY INT NOT NULL,
TOTAL DECIMAL(10,2) NOT NULL,
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

-- listando pedidos com número do item
SELECT O.ID, COUNT(OP.ID)
FROM ORDERS O
JOIN ORDER_PRODUCTS OP ON OP.ORDER_ID = O.ID
ORDER BY O.ID;







